# Generated by Django 2.2.7 on 2019-12-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='autor',
            new_name='producent',
        ),
    ]
