# Generated by Django 2.2.7 on 2019-12-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0008_auto_20191228_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='com',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.Product'),
        ),
    ]
