# Generated by Django 2.2.7 on 2019-12-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0011_auto_20191228_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='Anonim', max_length=50),
        ),
    ]
